require('pack.blink')
require('pack.oil')
require('pack.mini-statusline')
require('pack.catppuccin')
require('pack.fzf-lua')
require('pack.fugitive')
-- require('pack.miniharp') --doesnt work right now
require('pack.flash')
require('pack.floaterm')
require('pack.mini')
require('pack.indent-blankline')
require('pack.hlargs')
require('pack.autopairs')
require('pack.undotree')
require('pack.rainbow-delimiters')
require('pack.toggler')
